apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  namespace: bluegreen-lab
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    app: rollout-bluegreen
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
  namespace: bluegreen-lab
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    app: rollout-bluegreen
