apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: analysis-lab
spec:
  args:
    - name: service-name
    - name: initial-delay
      value: 5s
    - name: success-threshold
      value: '0.95'
  metrics:
    - name: success-rate
      interval: 5s
      count: 20
      initialDelay: '{{args.initial-delay}}'
      successCondition: result[0] >= {{args.success-threshold}}
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local:80
          query: |
            sum(rate(http_request_duration_seconds_count{code!~"[45].*", service="{{args.service-name}}"}[1m]))
            /
            sum(rate(http_request_duration_seconds_count{service="{{args.service-name}}"}[1m]))
