apiVersion: v1
kind: Service
metadata:
  name: blue-green-active
  namespace: analysis-lab
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    prometheus.io/path: '/metrics'
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: analysis-blue-green
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-preview
  namespace: analysis-lab
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    prometheus.io/path: '/metrics'
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: analysis-blue-green
