apiVersion: v1
kind: Service
metadata:
  name: rollout-gateway-stable
  namespace: gateway-lab
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: rollout-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-gateway-canary
  namespace: gateway-lab
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: rollout-gateway
